name: Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Print Current Date
        run: date --utc +"%Y-%m-%dT%H:%M:%S.%3NZ"

      - name: Install Dependencies
        run: npm install
      - name: Start Server
        run: npm start &
      - name: Run Cypress Tests
        run: npm run cypress:run
